#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
#mybatis.type-aliases-package=com.leo.springboot.mybatis.entity
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.leo.springboot.mybatis.entity


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#    type: com.alibaba.druid.pool.DruidDataSource
# 这里其实就是已经用了druid了，你可以认为他就是为了提升数据库查询用的




